### ISSUE TITLE
Add configuration example for docker

### ISSUE THREAD

**Issue by selfmadeking** [imbo/behat-api-extension#82]
Hi. 
I'd be great, if you could add information about [`base_uri` configuration](https://github.com/imbo/behat-api-extension/blob/master/docs/installation/configuration.rst) for projects, which use docker containers. I couldn't find any help for that for a few days. Finally i found solution in some docker hub documentation.

In base_uri we have to add string in a following construction:
`base_url: '{https/http}://{web server name}:{internal port}'`
example:
docker-compose.yml
```
version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx_container
        ports:
          - "82:80"
        volumes:
            - './app:/var/www/app'
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf      
// php, database containers etc
```

behat.yml
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Imbo\BehatApiExtension\Context\ApiContext
  extensions:
    Imbo\BehatApiExtension:
      apiClient:
        base_uri: http://nginx_container:80
```
